(function(){ovi.provide("nokia.maps.util.ColorHelper");
(function(d){function k(a){var b;if(a.charAt(0)==="#")b=e[a.length]?a:null;else if(a.substr(0,3)==="rgb"){b=a.match(/\d+(\.\d+)?/g);var g=b.length;b=g>2&&g<5?["#",c(+b[0]),c(+b[1]),c(+b[2]),g>3?c(+b[3]*255):"ff"].join(""):null}b||d.c("Invalid color definition: "+a);return b}function h(a){return!/^(#|rgb).*/.test(a)}function c(a){return a<16?"0"+g(a).toString(16):g(a).toString(16)}function b(b){b=a(b,16);return(b<<4)+b}var g=Math.round,a=parseInt,e={4:function(a){return["#",a.charAt(1),a.charAt(1),
a.charAt(2),a.charAt(2),a.charAt(3),a.charAt(3),"ff"].join("")},5:function(a){return["#",a.charAt(1),a.charAt(1),a.charAt(2),a.charAt(2),a.charAt(3),a.charAt(3),a.charAt(4),a.charAt(4)].join("")},7:function(a){return a+"ff"},9:function(a){return a}},l={4:function(a){return[b(a.charAt(1)),b(a.charAt(2)),b(a.charAt(3)),255]},5:function(a){return[b(a.charAt(1)),b(a.charAt(2)),b(a.charAt(3)),b(a.charAt(4))]},7:function(b){b=a(b.substring(1),16);return[b>>16&255,b>>8&255,b&255,255]},9:function(b){b=a(b.substring(1),
16);return[b>>24&255,b>>16&255,b>>8&255,b&255]}};d.ColorHelper={toInternal:function(a){return h(a)?a:(a=k(a),e[a.length]?e[a.length](a):a)},toRGBA:function(a,b){return h(a)?[0,0,0,255]:(b||(a=k(a)),l[a.length](a))},getHex3:function(a,b){return h(a)?a:(b||(a=k(a),a=e[a.length]?e[a.length](a):a),a.substr(0,7))},getAlpha:function(b,c){return h(b)?1:(c||(b=k(b),b=e[b.length]?e[b.length](b):b),a(b.substr(7,2),16)/255)},toRandomRGBA:function(a,b){if(h(a))return"000000ff";else{for(var a=this.toRGBA(a,b),
e=0;e<4;e++)a[e]=""+c(e<3?Math.floor(Math.random()*(a[e]-0+1))+0:a[e]);return a.join("")}}}})(nokia.maps.util);ovi.provide("nokia.maps.map.provider.IData");ovi.provide("nokia.maps.map.provider.IObjectProvider");ovi.provide("nokia.maps.util.proto");
(function(){var d={}.toString,k=nokia.maps.util.proto=function(h,c,b,g){var a=Function(),e,l;a.prototype=c;a=new a;for(e in h)h.hasOwnProperty(e)&&(a[e]=b&&e in c&&d.call(l=h[e])==="[object Object]"?k(l,c[e],b):h[e]);if(b&&!g)for(e in c)if(c.hasOwnProperty(e)&&(l=c[e])===a[e]&&d.call(l)==="[object Object]")a[e]=k(0,l,b);return a}})();ovi.provide("nokia.maps.map.HitArea");
(function(){var d=Math,k=d.PI/180,h=d.ceil,c=d.min,b=d.sin,g=d.cos,a=nokia.maps.util,e=a.Point,l=nokia.maps.map.HitArea=new ovi.Class({initialize:function(f,e){var d=(e=[].concat(e)).length,l=d,q,y,s,u,w;this.values=e;for(this.type=f;l--;)isNaN(e[l]=e[l])&&a.c("Given argument is not the array of numbers");f==="rect"&&d>3&&(e=[+e[0],+e[1],+e[2],+e[1],+e[2],+e[3],+e[0],+e[3]],f="poly");if(f==="circle"&&d>2&&(s=+e[2])>0){q=+e[0];y=+e[1];l=c(h(s)*2,40);u=360/l;for(e=[];l--;)w=u*l*k,e.push(q+b(w)*s,y+
g(w)*s);f="poly"}if(f==="poly"&&d&&!(e.length%2))this.zb=e;!this.zb&&a.c("bad polygon")},Statics:{from:function(a){return a instanceof l?a:new l(a.type,a.values?a.values:a.coords)}},hitTest:function(a,b,c){return e.isCoveredBy(a,b,this.zb,c,!0)}})})();ovi.provide("nokia.maps.map.provider.NullObjectProvider");
(function(d){d.map.provider.NullObjectProvider=new ovi.Class({zf:function(){},mh:function(){},mc:function(){},requestBBox:function(){return[]},cancelBBoxRequest:function(){},adopt:function(d){if(d.k)return!1;d.k=this;return d},orphan:function(d){if(d.k!==this)return!1;d.k=null;return d}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.Click");
(function(d){var k=d.map.component;k.panning.Click=new ovi.Class({Extends:k.Component,d:"panning.Click",n:"0.0.0.1",initialize:function(d){function c(e){b.enabled&&a.setCenter(a.pixelToGeo(e.targetX,e.targetY),"default")}var b=this,g=k.Component.prototype,a;b._super(ovi.extend({enabled:!0,useKineticPanning:!0},d));b.attach=function(e){g.attach.call(b,e);a=e;a.addListener("click",c)};b.detach=function(e){g.detach.call(b,e);a.removeListener("click",c)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.panorama.Click");
(function(d){var k=d.map.component;k.panning.panorama.Click=new ovi.Class({Extends:k.Component,d:"panning.panorama.Click",n:"0.0.0.1",initialize:function(d){function c(e){b.enabled&&e.button===0&&a.setView(a.m.viewForXY(e.targetX,e.targetY),"default")}var b=this,g=k.Component.prototype,a;b.q=b.PANORAMA;b._super(ovi.extend({enabled:!0,useKineticPanning:!0},d));b.attach=function(e){g.attach.call(b,e);a=e;a.addListener("click",c)};b.detach=function(e){g.detach.call(b,e);a.removeListener("click",c)}}})})(nokia.maps);
ovi.provide("nokia.maps.map.component.panning.Kinetic");(function(d){var k=d.map.component,h=k.panning;if(!d.util.getConstructor(h.Kinetic))h.Kinetic=new ovi.Class({Extends:k.Component,d:"panning.Kinetic",n:"0.0.0.1",initialize:function(c){this._super(ovi.extend({current:null},c))},attach:function(c){this._super(c);c.ug=!0},detach:function(c){this._super(c);c.ug=!1}})})(nokia.maps);ovi.provide("nokia.maps.map.render.Capabilities");
(function(){if(!nokia.maps.util.getConstructor(nokia.maps.map.render.Capabilities))var d=nokia.maps,k={min:0,max:0},h=(d.map.render.Capabilities=function(c){return d.util.proto(c,h,!0,!0)}).prototype={view:{heading:k,tilt:k,incline:k,distance:k,zoom:{min:-1/0,max:1/0}},cam:{fov:{min:70,max:70}},altMode:{GL:!0,OL:!1,SL:!1,SB:!1,WE:!1,WG:!1},provider:{tile:{bmp:!0,gfx:!1,mesh:!1},object:{spatial:!0,marker:!0,decal:!1}},ui:17,capture:!1,ZOOM:1,HEADING:2,TILT:4,INCLINE:8,COORD:16,FOV:32,SIZE:64}})();
ovi.provide("nokia.maps.map.component.panning.Tap");
(function(d){var k=d.map.component;k.panning.Tap=new ovi.Class({Extends:k.Component,d:"panning.Tap",n:"0.0.0.1",initialize:function(d){function c(e){b.enabled&&a.setCenter(a.pixelToGeo(e.targetX,e.targetY),"default")}var b=this,g=k.Component.prototype,a;b.q=b.MAP_2D;b._super(ovi.extend({enabled:!0,useKineticPanning:!0},d));b.attach=function(e){g.attach.call(b,e);a=e;a.addListener("tap",c)};b.detach=function(e){g.detach.call(b,e);a.removeListener("tap",c)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.DoubleClick");
(function(d){var k=d.map.component;k.zoom.DoubleClick=new ovi.Class({Extends:k.Component,d:"zoom.DoubleClick",n:"0.0.0.1",initialize:function(){function d(a){var f=g.getZoom(a.displayX,a.displayY);if(b.enabled){var c=a.button===2;(e=g.getComponentById("panning.Kinetic"))&&e.set("current",null);g.setZoomLevel(Math[c?"floor":"ceil"](f+(c?-1:1)),"default",a.displayX,a.displayY);a.cancel()}}function c(a){b.enabled&&a.preventDefault()}var b=this,g,a=k.Component.prototype,e;b.q=b.MAP_2D|b.GLOBE;b._super({enabled:!0});
b.attach=function(e){a.attach.call(b,e);g=e;g.addListener("dblclick",d);g.addListener("contextmenu",c)};b.detach=function(e){a.detach.call(b,e);g.removeListener("dblclick",d);g.removeListener("contextmenu",c)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.DoubleTap");
(function(d){var k=d.map.component;k.zoom.DoubleTap=new ovi.Class({Extends:k.Component,d:"zoom.DoubleTap",n:"0.0.0.1",initialize:function(){function d(a){var l=b.getZoom(a.displayX,a.displayY);c.enabled&&((g=b.getComponentById("panning.Kinetic"))&&g.set("current",null),b.pixelToGeo(a.displayX,a.displayY),b.setZoomLevel(l+1,"default",a.displayX,a.displayY),a.cancel())}var c=this,b,g,a=k.Component.prototype;c.q=c.MAP_2D;c._super({enabled:!0});c.attach=function(e){a.attach.call(c,e);b=e;b.addListener("dbltap",
d)};c.detach=function(e){a.detach.call(c,e);b.removeListener("dbltap",d)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.GestureEvent");
(function(d){var d=d.map.component,k,h,c=ovi.Array.forEach,b=ovi.Array.indexOf,g=d.Component.prototype,a=["gesturestart","gestureend","gesturechange","touchstart","touchmove","touchend"];d.zoom.GestureEvent=new ovi.Class({Extends:d.Component,d:"zoom.GestureEvent",n:"0.0.0.1",initialize:function(){h=this;h.q=h.MAP_2D;h._super();h.attach=function(b){g.attach.call(h,b);k=b;c(a,function(a){k.addEvent(a)})};h.detach=function(b){g.detach.call(h,b);c(a,function(a){k.removeEvent(a)})}},addListener:function(e,
c){if(b(a,e)>=0)return k.addListener(e,c),!0;return!1},removeListener:function(e,c){if(b(a,e)>=0)return k.removeListener(e,c),!0;return!1}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.MouseWheel");
(function(d){d.map.component.zoom.MouseWheel=new ovi.Class({Extends:d.map.component.Component,d:"zoom.MouseWheel",n:"0.0.0.1",initialize:function(){function k(a){e||(h(a)(),e=setTimeout(function(){l!==a&&h(a)();e=null},100));l=a}function h(f){return function(){var e=b.getZoom(f.displayX,f.displayY);c.enabled&&(b.setZoomLevel(f.shiftKey?e+f.wheelDelta/20:a[f.wheelDelta](e+f.wheelDelta),"default",f.displayX,f.displayY),f.cancel())}}var c=this,b,g=d.map.component.Component.prototype,a={"-1":Math.floor,
1:Math.ceil},e,l;c.q=c.MAP_2D|c.GLOBE;c._super({enabled:!0});c.attach=function(a){g.attach.call(c,a);b=a;b.addListener("mousewheel",k)};c.detach=function(a){g.detach.call(c,a);b.removeListener("mousewheel",k)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.panorama.MouseWheel");
(function(d){d.map.component.zoom.panorama.MouseWheel=new ovi.Class({Extends:d.map.component.Component,d:"zoom.panorama.MouseWheel",n:"0.0.0.1",initialize:function(){function k(b){if(h.enabled){var a=c.getCam();a.fov-=b.wheelDelta;c.setCam(a);b.cancel()}}var h=this,c,b=d.map.component.Component.prototype;h.q=h.PANORAMA;h._super({enabled:!0});h.attach=function(d){b.attach.call(h,d);c=d;c.addListener("mousewheel",k)};h.detach=function(d){b.detach.call(h,d);c.removeListener("mousewheel",k)}}})})(nokia.maps);
ovi.provide("nokia.maps.map.component.zoom.Gesture");
(function(d){var k=d.map.component;k.zoom.Gesture=new ovi.Class({Extends:k.Component,d:"zoom.Gesture",n:"0.0.0.1",initialize:function(){this.q=this.MAP_2D;this.onGestureStart=ovi.bind(this,this.onGestureStart);this.onGestureEnd=ovi.bind(this,this.onGestureEnd);this.onTouch=ovi.bind(this,this.onTouch);this._super({enabled:!0})},gc:!1,lc:!1,onGestureStart:function(d){if(this.enabled)this.gc=!0,d.preventDefault()},onGestureEnd:function(d){if(this.enabled)this.lc=this.gc=!1,this.mapDisplay.m.endInteraction(),
d.preventDefault()},onTouch:function(d){if(this.enabled&&this.gc){var c=this.mapDisplay.m,b=d.touches,d=d.timeStamp,g=b[0].pageX,a=b[0].pageY,e=b[1].pageX,b=b[1].pageY;this.lc?c.interact(d,g,a,e,b):(c.beginInteraction(c.capabilities.ZOOM|c.capabilities.COORD,null,d,g,a,e,b),this.lc=!0)}},attach:function(d){var c;this._super(this,d);this.mapDisplay=d;this.pg=c=new k.zoom.GestureEvent;d.addComponent(c);c.addListener("gesturestart",this.onGestureStart);c.addListener("gestureend",this.onGestureEnd);c.addListener("touchstart",
this.onTouch);c.addListener("touchmove",this.onTouch)},detach:function(d){var c=this.pg;this._super(this,d);this.mapDispay=null;d.removeComponent(c);c.removeListener("gesturestart",this.onGestureStart);c.removeListener("gestureend",this.onGestureEnd);c.removeListener("touchstart",this.onTouch);c.removeListener("touchmove",this.onTouch);this.pg=null;this.lc=this.gc=!1},enableRotation:function(){},disableRotation:function(){this.gu=!1},enableZoom:function(){this.un=!0},disableZoom:function(){this.un=
!1}})})(nokia.maps);ovi.provide("nokia.maps.map.Object");
(function(d){if(!d.util.getConstructor(d.map.Object)){var k=0,h=0,c=function(b,a){var e=b.ya(),c=a.ya(),f,d,m,k=0,q;if(!e||!c)return 0;f=e.length;d=c.length;for(m=f<d?f:d;k<m;k++)if(q=c[k]-e[k])return h?-q:q;return h?f-d:d-f},b={rev:0,sort:function(b,a,e){var d=[],f,p,m=b.length;for(p=0;p<m;p++)((f=b[p]).getIconForRendering||f.drawToTile)&&(a||f.isVisible())&&d.push(f);h=e;d.sort(c);return d},create:function(b){var a=b.f,e;e=null;a&&(e=(e=a.ya())?e.slice():[],e.push(b.zIndex,a.objects.indexOf(b)));
return e}};nokia.maps.map.Object=new ovi.Class({Extends:d.util.OObject,Mixins:d.dom.EventTarget,Statics:{sortByZInfo:b.sort,CHANGE_SPATIAL:1,CHANGE_VISUAL:2,CHANGE_ZINDEX:4},initialize:function(b){this.k=new d.map.provider.NullObjectProvider;this.id=k++;this._super(b);this.addObserver("*",this.Ab,this)},f:null,CHANGE_SPATIAL:1,CHANGE_VISUAL:2,CHANGE_ZINDEX:4,isEventTarget:!0,zIndex:0,visibility:!0,s:"object",Wc:function(){return this.qb||(this.qb={})},destroy:function(){var b=this.f;b&&b.objects.remove(this);
this.removeAllListeners();this.k=null;this.removeObserver("*",this.Ab,this)},getInvalidations:function(b){var a=this.qb;return a?(a[1]>b)*1|(a[2]>b)*2|(a[4]>b)*4:0},Ab:function(b,a){this.Y(a,0)},getProvider:function(){return this.k},getParent:function(){return this.f},getRoot:function(){for(var b=this,a=null;b=b.f;)a=b;return a},getDisplay:function(){var b=this.getRoot();return b&&b.s==="display"?b:null},isVisible:function(){var b=this,a=!1;do a=b.visibility;while(a&&(b=b.f));return a},Y:function(b,
a){var e;e=this.k;var c;a|=b==="zIndex"?4:b==="visibility"?2:0;c=e.mc(this,a);e=this.Wc();a&1&&(e[1]=c);a&2&&(e[2]=c);a&4&&(e[4]=c)},zIndexSetter:function(b){this.rb();return b},eventListenerSetter:function(b){var a=0,e,c;if(b)for(c in this.removeAllListeners(),b)if((a=ovi.type(e=b[c]))==="array")for(a=0;a<e.length;a+=3)this.addListenerNS(e[a+2],c,e[a],e[a+1]);else a==="function"&&this.addListenerNS(null,c,e,!1)},ya:function(){var c;if(!(c=this.Nb))c=this.Nb=b.create(this);return c},rb:function(){this.Nb=
void 0},adopt:function(b){return b.adopt(this)},orphan:function(){return this.k.orphan(this)}})}})(nokia.maps);ovi.provide("nokia.maps.map._MarkerIcon");
(function(){function d(a){if(typeof a==="object"&&a.strokeColor)a.strokeColor=c.ColorHelper.getHex3(a.strokeColor);if(a instanceof g)return a;else if(typeof a==="object")return new g(a);return new g({strokeColor:c.ColorHelper.getHex3(a)})}var k=nokia.maps,h=k.map.HitArea,c=k.util,b=c.Point,g=c.Pen,a=c.Brush,e=k.gfx.GraphicsImage,l=new k.gfx.SvgParser,f=c.uc("shape text textPen pen brush effect"),p=c.flatMerge(c.uc("anchor hitArea"),f),m=nokia.maps.map.jb=new ovi.Class({Extends:nokia.maps.util.OObject,
initialize:function(a){var b;a&&"shape"in a?(this.shape=this.shapeSetter(b=a.shape),delete a.shape,this._super(a),a.shape=b):(this.shape=this.shapeSetter(this.shape),this._super(a));this.addObserver("*",this.yd)},Statics:{hm:p,Da:function(a){return a in p},Kd:function(a){return!(a in f)},Gb:{balloon:['<path style="opacity:0.4;fill:#353535" d="m 68.999,117 c 0,1.668 -2.687,3 -6.001,3 c -3.312,0 -5.999,-1.332 -5.999,-3 c 0,-1.666 2.688,-3 5.999,-3 c 3.314,0 6.001,1.334 6.001,3 z" transform="translate(-50,-86)"/><path style="fill:__PEN__" d="m 106,-21 c -3.472,0 -6.7335,1.325 -9.1875,3.75 C 94.3585,-14.824 93,-11.58625 93,-8.15625 c 0,3.432 1.3585,6.6385 3.8125,9.0625 L 106,10 l 9.1875,-9.09375 c 2.455,-2.426 3.8125,-5.6325 3.8125,-9.0625 c 0,-3.428 -1.3575,-6.66575 -3.8125,-9.09375 C 112.7325,-19.675 109.474,-21 106,-21 z" transform="translate(-93,21)"/><path style="fill:#ffffff" d="m 106,-20 c -3.207,0 -6.234,1.22975 -8.5,3.46875 c -2.264,2.237 -3.5,5.217 -3.5,8.375 c 0,3.16 1.236,6.139 3.5,8.375 l 8.5,8.375 l 8.5,-8.375 c 2.264,-2.236 3.5,-5.215 3.5,-8.375 c 0,-3.158 -1.236,-6.137 -3.5,-8.375 C 112.233,-18.77025 109.209,-20 106,-20 z" transform="translate(-93,21)"/><path style="fill:__BRUSH__;fill-opacity:1" d="m 62.998,88.1875 c -6.984391,0 -10.738298,4.963982 -10.8105,10.6525 c 0,3.268 0.9535,5.611 3.0255,7.658 l 7.785,7.691 l 7.789,-7.691 c 2.072,-2.047 3.0255,-4.268 3.0255,-7.658 C 73.584296,93.067975 69.982391,88.1875 62.998,88.1875 z" transform="translate(-50,-86)"/><text x="13" y="18" font-size="10pt" font-family="arial" font-weight="bold" text-anchor="middle" fill="__TEXTPEN__" textContent = "__TEXTCONTENT__">__TEXT__</text>',
28,36,13,31,"poly",[0,16,0,7,8,0,18,0,26,7,26,16,18,34,8,34]]}},text:"",pen:new g({strokeColor:"#FFF"}),textPen:new g({strokeColor:"#FFF"}),brush:new a({color:"#1080DD"}),shape:"balloon",effect:"none",yd:function(a,b){if(b in f)a.za=0},shapeSetter:function(a){var f=this.Gm=m.Gb[a]||c.c("shape");this.o=new b(f[1],f[2]);this.anchor=new b(f[3],f[4]);this.hitArea=f[5]?new h(f[5],f[6]):void 0;return a},brushSetter:function(b){if(typeof b==="object"&&b.color)b.color=c.ColorHelper.getHex3(b.color);if(b instanceof
a)return b;else if(typeof b==="object")return new a(b);return new a({color:c.ColorHelper.getHex3(b)})},penSetter:d,textPenSetter:d,textSetter:function(a){return c.sanitizeText(a)},getIcon:function(){if(this.za)return this.za;var a=m.Gb[this.shape],b=a[1],f=a[2];return this.za=new e(l.parseSvg('<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="'+b+'" height="'+f+'" viewBox="0 0 '+b+" "+f+'">'+a[0].replace("__TEXTCONTENT__",this.text).replace("__TEXT__",this.text).replace("__TEXTPEN__",this.textPen.strokeColor).replace("__PEN__",
this.pen.strokeColor).replace("__BRUSH__",this.brush.color)+"</svg>"))}})})();ovi.provide("nokia.maps.map.Marker");
(function(){var d=nokia.maps,k=d.util,h=d.dom,c=d.map,b=d.gfx,g=k.Point,a=k.Strip,e=new g(0,0),l=k.Rectangle,f=c.jb,p=d.geo,m=c.HitArea,r=p.Coordinate,d=new ovi.Class({Extends:c.Object,initialize:function(a,b){var e;if(this.s==="marker"&&(!b||!("icon"in b)))e=new f,this.set("icon",e.getIcon()),this.set("anchor",e.anchor),this.set("hitArea",e.hitArea);this.Aa={};this._super(b);this.set("coordinate",a,1)},s:"marker",anchor:e,o:e,coordinateSetter:function(a){(a=r.fromObject(a))||k.c();this.Aa={};return a},
hitAreaSetter:function(a){return!a?a:m.from(a)},anchorSetter:function(a){(a=g.fromObject(a))||k.c("you have to set util.Point");return a},ua:function(a){this.o=new g(a.width,a.height);this.Hb=1},iconSetter:function(a){ovi.type(a);a instanceof b.Image||(a=b.Image.fromObject(a));a instanceof b.Image||k.c("icon");this.icon=a.B===document?a:a.clone(document);a.state===1?this.ua(a):this.Hb=0;return this.icon},getBoundingBox:function(){return p.BoundingBox.coverAll([this.coordinate])},getDisplayBoundingBox:function(a){a=
a.geoToPixel(this.coordinate).sub(this.anchor);return new l([a,a.add(this.o)])},hitTest:function(a,b,f,e){var a=this.getDisplayBoundingBox(a),c=new g(b,f),d=this.hitArea;return a.contains(c)&&(!d||d.hitTest(b-a.topLeft.x,f-a.topLeft.y,e))},getDisplayOffset:function(a,b,f){return(new g(b,f)).sub(a.geoToPixel(this.coordinate))},Y:function(a,b){a!=="zIndex"&&(b|=a==="coordinate"?1:2);this._super(a,b)},zd:function(a){var b="error";a.state===1&&(this.ua(a),this.Y("icon",2),b="load");this.dispatch(new h.Event({type:b,
target:this,relatedTarget:a}))},getIconForRendering:function(a){var b=this.icon;a!==document&&(b=b.clone(a));b.state?this.Hb||b.state===1&&this.ua(b):b.prepare(this.zd,this);return b},project:function(b){return this.Aa[b.id]||(this.Aa[b.id]=b.geoToMapPoints(a.stencil(a.LAT_LNG,[this.coordinate.latitude,this.coordinate.longitude])))}});if(c.Marker.isNs)c.Marker=d})();ovi.provide("nokia.maps.map.StandardMarker");
(function(){function d(b,c,a){b.R.set(c,a);if(c==="shape")b.o=b.R.o,b.set("anchor",b.R.anchor),b.set("hitArea",b.R.hitArea);return b.R[c]}var k=nokia.maps,h=k.util,c=k.map.jb,k=nokia.maps.map.StandardMarker=new ovi.Class({Extends:nokia.maps.map.Marker,initialize:function(b,d){var a=this.R=new c(h.flatMerge({},d,1,c.Da));h.flatMerge(this,a,1,c.Da);this.o=a.o;this._super(b,h.flatMerge({},d,1,c.Kd))},s:"standardmarker",shapeSetter:function(b){return d(this,"shape",b)},textSetter:function(b){return d(this,
"text",b)},textPenSetter:function(b){return d(this,"textPen",b)},penSetter:function(b){return d(this,"pen",b)},brushSetter:function(b){return d(this,"brush",b)},getIconForRendering:function(b){this.set("icon",this.R.getIcon());return this._super(b)}});h.flatMerge(k.prototype,c.prototype,!0,c.Da)})();ovi.provide("nokia.maps.map.component.panning.Drag");
(function(d){function k(a){return 1*a.altKey+2*a.ctrlKey+4*a.metaKey+8*(a.button===2||a.button===0&&(a.shiftKey||h&&a.ctrlKey))}var h=d.dom.Page.platform.mac,c=d.map,b=c.component,g=new c.render.Capabilities,a={duration:function(){return 600},ease:d.util.animation.easeFunctions.LINEAR,power:function(){return 1}};b.panning.Drag=new ovi.Class({Extends:b.Component,d:"panning.Drag",n:"0.0.0.1",initialize:function(e){function c(a){m.enabled&&(f(a),q.endInteraction(),q.setTransition(q.ma.TRANSITION.AUTO))}
function f(a){var b=a.dataTransfer;if(m.enabled&&b&&b.getData("application/map-drag-type")==="map"){var b=a.deltaX,f=a.deltaY;k(a)!==y?d(a):((b||f)&&q.interact(a.timeStamp,a.displayX,a.displayY),a.stopImmediatePropagation())}}function d(b){var e;if(m.enabled)e=b.dataTransfer,y=k(b),e.cursor=y&8?"move":"hand",e.lift=!1,e.setData("application/map-drag-type","map"),e.setData("application/map-drag-object",q),e.setData("application/map-drag-object-offset",void 0),q.setTransition(q.ma.TRANSITION.NONE),
q.beginInteraction(y&8?g.HEADING|g.TILT:g.COORD,q.ug?a:"",b.timeStamp,b.displayX,b.displayY),f(b)}var m=this,h=b.Component.prototype,q,y;m.q=m.PANORAMA|m.MAP_2D|m.GLOBE;m._super(ovi.extend({enabled:!0,useKineticPanning:!0},e));m.attach=function(a){h.attach.call(m,a);q=a;q.addListener("dragstart",d);q.addListener("drag",f);q.addListener("dragend",c)};m.detach=function(a){h.detach.call(m,a);q.removeListener("dragstart",d);q.removeListener("drag",f);q.removeListener("dragend",c)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.objects.DragMarker");
(function(d){var k=d.util.Point,d=d.map,h=d.component,c=d.Marker,b=c.prototype.s,g=d.StandardMarker.prototype.s;h.objects.DragMarker=new ovi.Class({Extends:h.Component,d:"objects.DragMarker",n:"0.0.0.1",dragSourceOpacity:1,dragIconOpacity:0.5,initialize:function(a){function e(a){var f=a.dataTransfer,e=f&&f.getData("application/map-drag-type"),d=f&&f.getData("application/map-drag-object");if((e===b||e===g)&&d instanceof c){if(d.f)f.dropEffect="none";else if(f.allows("move"))f.dropEffect="move";else{f.dropEffect=
"none";a.cancel();return}e=f.getData("application/map-drag-object-offset")||new k(0,0);d.set("coordinate",s.pixelToGeo(a.displayX-e.x+d.anchor.x,a.displayY-e.y+d.anchor.y));f.dropEffect!=="none"&&s.objects.add(d);a.cancel()}else f.dropEffect="none"}function d(a){var f=a.dataTransfer,e=f&&f.getData("application/map-drag-type"),c=f&&f.getData("application/map-drag-object");if(e===b||e===g)f.dropEffect=c.f?"move":"copy",a.cancel()}function f(a){var f=a.dataTransfer,e=f&&f.getData("application/map-drag-type"),
c=f&&f.getData("application/map-drag-object");if(e===b||e===g)f.dropEffect=c.f?"move":"copy",a.cancel()}function p(a){var f=a.dataTransfer,e=f&&f.getData("application/map-drag-type"),c=f&&f.getData("application/map-drag-object");f&&f.getData("application/map-drag-object-display");if(e===b||e===g){c.removeListener("dragend",p,!0);if(f.dropEffect==="move"&&!s.contain(c))dragMarkerParent=c.f,dragMarkerParent.objects.remove(c);c.icon.opacity=1;c.Y("icon",2);a.stopImmediatePropagation()}}function m(a){var f=
a.dataTransfer,f=f&&f.getData("application/map-drag-type");(f===b||f===g)&&a.stopImmediatePropagation()}function r(a){if(q.enabled){var b,f,e,d=a.target,g=a.dataTransfer;if(d instanceof c&&d.draggable)f=d.getDisplayBoundingBox(s),b=a.displayX-f.topLeft.x,f=a.displayY-f.topLeft.y,e=d.getIconForRendering(document),g.setDragImage(e.createElement(q.dragIconOpacity),-b,-f),d.icon.opacity=q.dragSourceOpacity,d.Y("icon",2),g.setData("application/map-drag-type",d.s),g.setData("application/map-drag-object",
d),g.setData("application/map-drag-object-offset",new k(b,f)),g.effectAllowed="all",g.setData("application/map-drag-object-display",s),d.insertListener("dragend",p,!0),a.stopImmediatePropagation()}}var q=this,y=h.Component.prototype,s;q.q=q.MAP_2D|q.GLOBE;q._super(ovi.extend({enabled:!0,useKineticPanning:!0},a));q.attach=function(a){y.attach.call(q,a);s=a;s.addListener("dragstart",r);s.addListener("drag",m);s.addListener("dragend",p);s.addListener("dragenter",f);s.addListener("dragover",d);s.addListener("drop",
e)};q.detach=function(a){y.detach.call(q,a);s.removeListener("dragstart",r);s.removeListener("drag",m);s.removeListener("dragend",p);s.removeListener("dragenter",f);s.removeListener("dragover",d);s.removeListener("drop",e)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.Behavior");
(function(d){var k=d.map.component;k.Behavior=new ovi.Class({Extends:k.Component,d:"Behavior",n:"0.0.0.1",initialize:function(){var d=this,c=ovi.bind,b,g,a,e,l,f,p,m,r,q;d.q=d.PANORAMA|d.MAP_2D;d.attach=function(y){d.mapDisplay=b=y;var y=c(b,b.addComponent),s=k.zoom,u=k.panning;g=s.MouseWheel&&y(new s.MouseWheel);a=s.DoubleClick&&y(new s.DoubleClick);e=s.DoubleTap&&y(new s.DoubleTap);l=s.Gesture&&y(new s.Gesture);f=u.Drag&&y(new u.Drag);p=u.Kinetic&&y(new u.Kinetic);q=k.objects.DragMarker&&y(new k.objects.DragMarker);
r=s.panorama.MouseWheel&&y(new s.panorama.MouseWheel);m=u.panorama.Click&&y(new u.panorama.Click)};d.detach=function(){delete d.mapDisplay;var k=c(b,b.removeComponent);g&&k(g);a&&k(a);e&&k(e);l&&k(l);f&&k(f);p&&k(p);q&&k(q);r&&k(r);m&&k(m);b=null}}})})(nokia.maps);ovi.provide("nokia.maps.behavior._packaging.package-all");})();
