/*
 * Copyright (C) 2009, Nokia gate5 GmbH Berlin
 *
 * These coded instructions, statements, and computer programs contain
 * unpublished proprietary information of Nokia gate5 GmbH, and are
 * copy protected by law. They may not be disclosed to third parties
 * or copied or duplicated in any form, in whole or in part, without
 * the specific, prior written permission of Nokia gate5 GmbH.
 */ 

this.nokia=this.nokia||{};nokia.places=nokia.places||{comm:{},data:{},utils:{},search:{},widgets:{},ui:{modules:{},templates:{blue:{},general:{},mobileHTML5:{},wordpress:{},st:{}}}};nokia.places.utils.enums={CssUrlModes:{NONE:"none",AGGREGATED:"aggregated",NON_AGGREGATED:"nonAggregated"}};
nokia.places.utils.util=function(){function h(c,f){var d=c,b;for(b in f)f.hasOwnProperty(b)&&(d=d.replace("{"+b+"}",f[b]));return d}function k(c,f){return function(){return c.apply(f,arguments)}}function i(c,f,d){var b=new Date;d&&b.setDate(b.getDate()+d);document.cookie=h("{NAME}={VALUE}{EXPIRES}",{NAME:c,VALUE:encodeURI(f),EXPIRES:d?"":"; expires="+b.toUTCString()})}function j(c){if(document.cookie.length){var f=document.cookie.indexOf(c+"=");if(-1!==f)return f=f+c.length+1,c=document.cookie.indexOf(";",
f),-1===c&&(c=document.cookie.length),decodeURI(document.cookie.substring(f,c))}return""}var e={en:"gb",da:"dk",cs:"cz",el:"gr",hi:"in",ko:"kr",sv:"se",zh:"cn"};return{mixin:function(c,f){for(var d=Array.prototype.slice.call(arguments,1),b=d.shift();b;){for(var a in b)b.hasOwnProperty(a)&&(c[a]=b[a]);b=d.shift()}return c},replace:h,inherit:function(c,f,d){var b=function(){};b.prototype=c.prototype;f.prototype=new b;for(var a in d)d.hasOwnProperty(a)&&(f.prototype[a]=d[a])},trim:function(c){return c.replace(/(^\s+)|(\s+$)/g,
"")},setCookie:i,getCookie:j,clearCookie:function(c){i(c,"",-1)},createTempUserId:function(){var c=j("ppTmpUser");c||(c=Math.floor(1E8*Math.random())+""+(new Date).getTime(),i("ppTmpUser",c,360));return c},addProtocolToUrl:function(c){0!==c.indexOf("http://")&&0!==c.indexOf("https://")&&(c="http://"+c);return c},ensureReplaced:function(c,f){return 0===c.indexOf("$")?f:c},removeTags:function(c){return"string"===typeof c?c.replace(/<([a-zA-Z0-9]*|\n)+>/g,"").replace(/<\/([a-zA-Z0-9]*|\n)+>/g,""):c},
escapeTags:function(c){return"string"===typeof c?c.replace(/</g,"&lt;").replace(/>/g,"&gt;"):c},extendWith:function(c,f){for(var d in f)f.hasOwnProperty(d)&&typeof("function"===f[d])&&(c[d]=k(f[d],c))},getBrowserLanguage:function(){var c="undefined"===typeof window?"en":window.navigator.userLanguage||window.navigator.language||"en";if(2===c.length){var f=e[c];return f?[c,f].join("-"):[c,c].join("-")}return c},getDefaultDialect:function(c){return e[c]?e[c]:c},toArray:function(c){return c instanceof
Array?c:[c]}}}();
nokia.places.settings=function(){function h(){var a=this.jslocation||nokia.maps;if(a&&a.util&&a.util.services)return a.util.services}function k(a){var c=h(),a=e(a,{S_URL:f,APPID:d,TOKEN:b,LANG:p});return c?c.addNlpParams(a):a}var i=nokia.places.utils.util,j=nokia.Settings,e=i.replace,c=i.ensureReplaced,f="http://places.nlp.nokia.com/places/v1",d="",b="",a=c("${cnContext}",!1),l="&app_id={APPID}&app_code={TOKEN}",g=[];g.push("callback=nokia.places.comm.data.clb['{CALLBACK_ID}']");h()?l="":g.push(l);
g.push("Accept-Language={LANG}");var g=g.join("&"),n="{S_URL}/discover/search/?"+g+"&",m="{S_URL}/suggest/?"+g+"&",q="{S_URL}/discover/explore/places?"+g+"&",a=a?"":"&int=true",o="{S_URL}/places/{PLACE_ID}?"+g,r="{S_URL}/places/{PLACE_ID}/media/images?offset={START}&size={LIMIT}&"+g,s="{S_URL}/places/{PLACE_ID}/media/reviews?offset={START}&size={LIMIT}&"+g,t="{S_URL}/places/{PLACE_ID}/related/recommended?size={LIMIT}&"+g,u="{S_URL}/reversegeocode.json?prox={LAT},{LONG},1000&gen=1&mode=retrieveAddresses&jsoncallback=nokia.places.comm.data.clb['{CALLBACK_ID}']"+
l+"&language={LANG}"+a,v="{S_URL}/geocode.json?gen=1&searchtext={LOC}&jsoncallback=nokia.places.comm.data.clb['{CALLBACK_ID}']"+l+a,p=i.getBrowserLanguage();j&&(d=j.app_id,b=j.app_code,j.addObserver("app_id",function(a){a!==d&&(d=a)}),j.addObserver("appId",function(a){a!==d&&(d=a)}),j.addObserver("app_code",function(a){a!==b&&(b=a)}),j.addObserver("authenticationToken",function(a){a!==b&&(b=a)}));i=function(){};i.prototype={getPlaceUrl:function(a){var b=k(o);return e(b,{PLACE_ID:a})},getPlaceImagesUrl:function(a,
b,c){var l=k(r);return e(l,{PLACE_ID:a,START:b||0,LIMIT:c||5})},getReviewsUrl:function(a,b){var c=k(s);return e(c,{PLACE_ID:a,LIMIT:b.limit||"5",START:b.start||"0"})},getRecommendationsUrl:function(a,b){var c=k(t);return e(c,{PLACE_ID:a,LIMIT:b||5})},getRatingUrl:function(a){return e("{S_URL}/{PLACE_ID}/ugc/ratings.js;callback={CALLBACK_ID}?",{PLACE_ID:a,S_URL:"http://api.places.maps.ovi.com/rest/v1/places"})},getRatingPostUrl:function(a){return e("{S_URL}/{PLACE_ID}/ugc/ratings?",{PLACE_ID:a,S_URL:"http://api.places.maps.ovi.com/rest/v1/places"})},
getSearchUrl:function(){return k(n)+"&"},getCategorySearchUrl:function(){return k(q)+"&"},getSuggestUrl:function(){return k(m)+"&"},getLocale:function(){return p},getClbTemplate:function(){return"callback=nokia.places.comm.data.clb['{CALLBACK_ID}']"},getReverseGeoUrl:function(a,c){var l=e(u,{LAT:a,LONG:c,S_URL:"http://geo.nlp.nokia.com/search/6.2",APPID:d,TOKEN:b,LANG:p}),g=h();return g?g.addNlpParams(l):l},getGeoCodeUrl:function(a){var a=e(v,{LOC:a,S_URL:"http://geo.nlp.nokia.com/search/6.2",APPID:d,
TOKEN:b,LANG:p}),c=h();return c?c.addNlpParams(a):a},setPlacesServerUrl:function(a){f=a},getPlacesServerUrl:function(){return f},getServices:h,setLocale:function(a){p=a},setAppContext:function(a){a=a||{};d=a.appId||a.app_id;b=a.authenticationToken||a.app_code;if(j){j.set("app_id",d);j.set("app_code",b)}},getAppContext:function(){return{app_id:d,app_code:b}},commTimeout:1E4,revision:c("-1","0"),version:c("beta5-SNAPSHOT","0")};i.prototype.constructor=i;return new i}();
nokia.places.comm.core=function(){function h(e){e&&e.parentNode&&e.parentNode.removeChild(e)}function k(){var e=j.getElementById(i);e||(e=j.createElement("div"),e.setAttribute("id",i),e.style.display="none",j.body.appendChild(e));return e}var i="nokiaPlacesTransport",j=document;return{get:function(e,c){var f=k(),d=j.createElement("script");d.setAttribute("src",e);d.setAttribute("type","text/javascript");"Microsoft Internet Explorer"===navigator.appName?d.onreadystatechange=function(){if("loaded"===
this.readyState||"complete"===this.readyState)h(this),"function"===typeof c&&c()}:d.onload=function(){h(this);"function"===typeof c&&c()};f.appendChild(d);return d},post:function(e,c,f,d){var b=k(),a=j.createElement("iframe");a.style.display="none";b.appendChild(a);setTimeout(function(){var b=a.contentWindow||a.contentDocument;a.doc=b.document?b.document:b;b=a.doc.createElement("form");b.method="post";b.action=e;b.setAttribute("accept-charset","utf-8");b.setAttribute("enctype","multipart/form-data");
b.setAttribute("encoding","multipart/form-data");var g=a.doc.createElement("input");g.type="text";g.name="user-id";g.value=d||"";b.appendChild(g);g=a.doc.createElement("input");g.type="text";g.name="entity";g.value=c;b.appendChild(g);a.doc.body.appendChild(b);var n=function(){setTimeout(function(){h(a)},1);"function"===typeof f&&f()};a.onload=function(){n()};a.onreadystatechange=function(){"complete"===this.readyState&&n()};b.submit()},1)}}}();
nokia.places.comm.data=function(){function h(){return""+ ++f}function k(d,b){var a=function(l,g){l&&400<=l.status&&(l={responseStatus:l.status,message:l.error_description||l.message},g="ERROR",window.console&&"function"===typeof window.console.error&&window.console.error("Error "+l.responseStatus+" - "+l.message));"function"===typeof b&&b(l,g||"OK");clearTimeout(a.timeout);delete c[d]};a.timeout=setTimeout(function(){window.console&&"function"===typeof window.console.error&&window.console.error("Timeout - cannot connect to the server");
a(null,"ERROR")},e.commTimeout);return a}var i=nokia.places,j=i.comm.core,e=i.settings,c={},f=100;return{performRequest:function(d,b,a){a=a||h();d=d.replace("{CALLBACK_ID}",a);c[a]=k(a,b);j.get(d,null,a);return a},performNoCbRequest:function(c){j.get(c)},performPostRequest:function(c,b,a,l){j.post(c,b,a,l)},abortRequest:function(d){if("undefinded"===typeof d||!c[d])return!1;c[d].timeout&&clearTimeout(c[d].timeout);c[d]=function(){delete c[d]}},getCallBackId:h,getSeed:function(){return f},clb:c}}();
(function(h){h.ovi=this.ovi||{};h.ovi.player={};h.ovi.player.places={};h.ovi.player.places.Com={};h.ovi.player.places.Com.data=function(h,i){nokia.places.comm.data.clb[""+h.callback](i)}})(this);
nokia.places.data.dataTransformer=function(){function h(b){return{latitude:b[0],longitude:b[1]}}function k(b){if(b instanceof Array)return{topLeft:{latitude:b[3],longitude:b[0]},bottomRight:{latitude:b[1],longitude:b[2]}}}function i(b){if(b)return{name:b.title,categoryId:b.id,icon:b.icon}}function j(b){var a;if(!b)return!1;if((a=b.results)&&a.next){var l=b.results.next;b.results.getNext=function(a){if(a&&a.onComplete){var b=a.onComplete;l+="&"+f.getClbTemplate();return c(l,function(a,c){"function"===
typeof b&&(c===d&&(a=j(a)),b(a,c))})}}}delete b.next;a=b.items||b.results.items;if(b.search){b.search.context&&(b.search.location=b.search.context.location,delete b.search.context);var g=b.search.location;g.position&&(g.position=h(g.position));g.bbox&&(g.boundingBox=k(g.bbox),delete g.bbox)}if(a)for(var g=0,e=a.length;g<e;g++){var m=a[g],q=m.href.match(/([\w\d]{8}-[\w\d]{32})/),o=m.category;o.icon=m.icon.replace(/(_\d{2})?\.icon/,".icon");m.id?(m.placeId=m.id,delete m.id):q&&q[1]&&(m.placeId=q[1]);
m.position=h(m.position);m.bbox&&(m.boundingBox=k(m.bbox),delete m.bbox);m.category=i(o);delete m.refId;delete m.type}return b}function e(b){if(!b)return!1;if(b.next){var a=b.next;b.getNext=function(b){if(b&&b.onComplete){var g=b.onComplete;a+="&"+f.getClbTemplate();return c(a,function(a,b){"function"===typeof g&&(b===d&&(a=e(a)),g(a,b))})}}}delete b.next;delete b.create;if(b.items)for(var l=0,g=b.items.length;l<g;l++){var n=b.items[l];if(n){var m=n.supplier;n.supplier={name:m.title,supplierId:m.id,
icon:m.icon};delete n.id}}return b}var c=nokia.places.comm.data.performRequest,f=nokia.places.settings,d="OK";return{transformPlace:function(b){if(!b)return!1;b.location.position=h(b.location.position);b.location.bbox&&(b.location.bbox=k(b.location.bbox));if(b.media){var a=b.media;a.reviews&&(a.reviews.available?a.reviews=e(a.reviews):delete a.reviews);a.editorials&&(a.editorials=e(a.editorials));a.images&&(a.images.available?a.images=e(a.images):delete a.images);a.links&&(a.links=e(a.links));a.images||
a.editorials||a.reviews||a.links?b.media=a:delete b.media}if(a=b.supplier)b.supplier={name:a.title,supplierId:a.id};for(var a=0,c=b.categories.length;a<c;a++)b.categories[a]=i(b.categories[a]);delete b.refId;return b},transformSearchResults:j,transformReverseGeo:function(b){if(b){var a={location:{}};a.location.position={latitude:parseFloat(b.Location.DisplayPosition.Latitude),longitude:parseFloat(b.Location.DisplayPosition.Longitude)};var c=a.location,b=b.Location.Address,g={},d,f,e;for(e in b)if(b.hasOwnProperty(e))if(f=
b[e],"AdditionalData"!==e)d="Label"===e?"text":"Country"===e?"countryCode":e.charAt(0).toLowerCase()+e.substr(1),g[d]=f;else{d=0;for(var h=f.length;d<h;d++){var i=f[d];"CountryName"===i.key?g.country=i.value:"StateName"===i.key&&(g.state=i.value)}}c.address=g;a.name=a.location.address.text;return a}},transformMediaObject:e,transformRating:function(b){var a={average:0,count:0};b&&(a={average:b.rating||0,count:b.ratingCount||0});return a}}}();
nokia.places.manager=function(){function h(b){if(b){var a=b.placeId,c=b.onComplete;if(a&&"function"===typeof c)return b=i.getPlaceImagesUrl(a,b.start,b.limit),e(b,function(a,b){b===d&&(a=f.transformMediaObject(a));c(a,b)})}}var k=nokia.places,i=k.settings,j=k.comm.data.performPostRequest,e=k.comm.data.performRequest,c=k.utils.util,f=k.data.dataTransformer,d="OK";return{getPlaceData:function(b){if(b){var a=b.onComplete;if((b.placeId||b.href)&&a)return b=b.href?b.href+"&"+i.getClbTemplate():i.getPlaceUrl(b.placeId),
e(b,function(b,c){c===d&&(b=f.transformPlace(b));"function"===typeof a&&a(b,c)})}},getRating:function(b){if(b){var a=b.placeId,d=b.onComplete;if(a&&d)return b=i.getRatingUrl(a),e(b,function(a,b){var e={count:0,average:0};if(a&&a.averageRatings&&a.averageRatings.averageRating)for(var h=c.toArray(a.averageRatings.averageRating),i,j=0,k=h.length;j<k;j++)i=h[j],"OVERALL"===i.ratingType&&(e=f.transformRating(i));d(e,b)})}},getReviews:function(b){if(b){var a=b.placeId,c=b.onComplete;if(a&&c)return b=i.getReviewsUrl(a,
b),e(b,function(a,b){"function"===typeof c&&(b===d&&(a=f.transformMediaObject(a)),c(a,b))})}},getMedia:h,getImages:h,postRating:function(b){if(b){var a=b.placeId,c=parseInt(b.ratingValue,10);if(a&&c){var c=5<c?5:1>c?1:c,a=i.getRatingPostUrl(a),c="{ratings:{rating:[{value:"+c+",type:'OVERALL'}]}}",d=k.utils.util.createTempUserId();j(a,c,b.onComplete,d)}}}}}();
nokia.places.search.nsp=function(){function h(a){var b=[],c=a.searchCenter;a.limit&&b.push("size="+encodeURIComponent(a.limit));a.searchTerm&&b.push("q="+encodeURIComponent(a.searchTerm));a.category&&b.push("cat="+encodeURIComponent(a.category));"object"===typeof a.boundingBox&&"object"===typeof a.boundingBox.topLeft&&"object"===typeof a.boundingBox.bottomRight?b.push("X-Map-Viewport="+a.boundingBox.topLeft.longitude+","+a.boundingBox.bottomRight.latitude+","+a.boundingBox.bottomRight.longitude+","+
a.boundingBox.topLeft.latitude):c&&("number"===typeof c.longitude&&"number"===typeof c.latitude)&&b.push("at="+c.latitude+","+c.longitude);return b.join("&")}function k(a,e){var g=d.getSearchUrl()+h(a);return c.performRequest(g,function(c,d){d===b&&(c=f.transformSearchResults(c),a.onComplete(c,d))},e)}function i(a,e){var g=d.getCategorySearchUrl()+h(a);return c.performRequest(g,function(c,d){d===b&&(c=f.transformSearchResults(c),a.onComplete(c,d))},e)}function j(a,e){var g=d.getSuggestUrl()+h(a);
return c.performRequest(g,function(c,d){if(d===b)a.onComplete(c,d)},e)}var e=nokia.places,c=e.comm.data,f=e.data.dataTransformer,d=e.settings,b="OK";return{search:function(a,b){var d=a.useGeoLocation,e,f,h={latitude:0,longitude:0},o=c.getCallBackId(),r=!0===b?j:a.category?i:k;try{e=navigator?navigator.geolocation:null}catch(s){}!f&&d&&e?(e.getCurrentPosition(function(b){f={latitude:b.coords.latitude,longitude:b.coords.longitude};a.searchCenter=f;r(a,o)},function(){a.searchCenter=h;r(a,o)},{timeout:6E3}),
f=h):(a.searchCenter=f||a.searchCenter||h,r(a,o));return o}}}();
nokia.places.search.manager=function(){var h=nokia.places,k=h.settings,i=h.search.nsp,j=h.comm.data.performRequest,e=h.data.dataTransformer;return{findPlaces:function(c){if(c&&c.searchTerm&&c.onComplete)return i.search(c)},findPlacesByCategory:function(c){if(c&&c.category&&c.onComplete)return i.search(c)},suggestPlaces:function(c){if(c&&c.searchTerm&&c.onComplete)return i.search(c,!0)},findRecommendations:function(c){if(c){var f=c.placeId,d=c.onComplete;if(f&&"function"===typeof d)return c=k.getRecommendationsUrl(f,
c.limit),j(c,function(b,a){"OK"===a?d(e.transformSearchResults(b),a):d({},a)})}},reverseGeoCode:function(c){var c=c||{},f=c.latitude,d=c.longitude,b=c.onComplete,c=k.getReverseGeoUrl(c.latitude,c.longitude);if(f&&d&&"function"===typeof b)return j(c,function(a){if(a&&a.Response&&a.Response.View)if(a.Response.View.length){for(var a=a.Response.View[0].Result,c,d=0,f=a.length;d<f;d++)if(c=a[d],c.Location.Address.Street){b(e.transformReverseGeo(c),"OK");return}b(e.transformReverseGeo(a[0]),"OK")}else b("",
"OK");else b(a?a.Details:"","ERROR")})},geoCode:function(c){var c=c||{},f=c.address,d=c.searchTerm,b=c.onComplete,a,h=[];if(c.onComplete&&(d||f)){if(f)for(a in f)f.hasOwnProperty(a)&&h.push(f[a]);else h.push(d);d=encodeURIComponent(h.join(","));c=k.getGeoCodeUrl(d);return j(c,function(a){a&&a.Response?a.Response.View&&a.Response.View[0]&&a.Response.View[0].Result?b(e.transformReverseGeo(a.Response.View[0].Result[0]),"OK"):b(null,"OK"):b(a,"ERROR")})}}}}();